[build]
  command = "yarn build"
  publish = "dist"

# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production context: all deploys from the Production branch set in your site's
# deploy contexts will inherit these settings.
[context.production]
  environment = { YARN_VERSION = "1.13.0", NODE_VERSION = "10.15.2" }